import _ from "lodash";

export const defaultTemplatesRow = {
    pos: "",
    cpt: "",
    modifier_a: "",
    modifier_b: "",
    modifier_c: "",
    modifier_d: "",
    diagnose_pointer: "",
    isUserChangesDiagnosePointer: false,
    isUserChangesModifierA: false,
    isUserChangesCharge: false,
    isDiagnosePointerError: false,
    charge: "",
    days_or_units: "",
    patient_insurances_procedure_id: "",
};

export const initialFormData = {
    inquirable_id: "",
    auth_number: "",
    first_name: "",
    last_name: "",
    middle_initial: "",
    date_of_birth: "",
    sex: "",
    preferred_language_id: "",
    email: "",
    secondary_email: "",
    cell_phone: "",
    home_phone: "",
    work_phone: "",
    preferred_phone: "",
    visits_auth: 0,
    visits_auth_left: 0,
    address: "",
    address_2: "",
    city: "",
    state: "",
    zip: "",
    provider_id: "",
    insurance_id: "",
    eff_start_date: "",
    eff_stop_date: "",
    subscriber_id: "",
    is_self_pay: false,
    self_pay: 0,
    visit_copay: 0,
    deductible: 0,
    deductible_met: 0,
    deductible_remaining: 0,
    insurance_pay: 0,
    eligibility_payer_id: "",
    plan_name: "",
    diagnoses: [],
    templates: [_.cloneDeep(defaultTemplatesRow)],
    therapist_manage_timesheet: false,
    is_payment_forbidden: false,
    source_id: null,
    therapy_type_id: null,
};
